prometheus:
  alertmanager:
    enabled: true
  grafana:
    enabled: false

  server:
    persistentVolume:
      enabled: true
      size: "50Gi"

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://my-monitoring-prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
  persistence:
    enabled: true
    type: pvc
    size: "10Gi"
